### PR TITLE
Remove inner class, override super-class methods instead.

### PR DESCRIPTION
**Pull request by lalongooo**

### CODE REVIEW

**Comment by sitexa** [comment]
I think presenter is not subscriber, I don't think it is a good idea to extends the DefaultSubscriber.

**Comment by johnwatsondev** [comment]
@sitexa I'm agree with you. :+1:

**Comment by spirosoik** [comment]
@sitexa Yeap that's true :+1:

**Comment by lalongooo** [comment]
@sitexa Thanks, I will close this PR, will send a second one.

**Pull request closed without merging**
