### PR TITLE
update gradles to make the build pass on Android Studio 3.0

### PR DESCRIPTION
**Pull request by LiLister**
I updated some build.gradle files to make the project synced and built successfully.
Android Studio 3.0 changed the default gradle tool version. and the gradle update introduces some new syntax for build.gradle.

### CODE REVIEW

**Comment by CoderSpinoza** [comment]
Seems license agreement is needed for CI to pass. I suppose the below link recommends the easiest solution.

https://stackoverflow.com/a/45782695/1509425

Just running 

```
yes | sdkmanager --licenses
```
before 

```
./gradlew build
```

When can this be merged?

**Comment by l3d00m** [comment]
@CoderSpinoza I think travis does it automatically if the `.travis.yaml` file is updated with the new build tools version, this is missing here

**Comment by LiLister** [comment]
The .travis.yml has been updated according to update of dependencies.gradle.

**Comment by soshial** [comment]
@LiLister , thank you so much for fixing this! It even works in Android Studio 4.1.1
I spend 2 hours trying to do it myself before giving up and using your PR.

**Review by android10 — APPROVED** [review]
👍🏻 thanks for the contribution.

**Comment by android10** [comment]
@LiLister merging right away! @soshial sorry for the radio silence. Sometimes it is hard to get time to attend many requests, plus this codebase was less maintained due to the efforts being put on the kotlin side of things. 

In any case, super happy to see people active here. I totally appreciate it! ❤️ 

One more time, thank you!

**Pull request merged**
