### PR TITLE
Single activity architecture

### PR DESCRIPTION
**Pull request by wkarl**
Great repo. However, I didn't like the multiple activity design.
This version only uses a single MainActivity and three fragments.

I am relatively new to dependency injection and Dagger2 so I'd appreciate any feedback you might have.

If you want this to go into a separate branch, just let me know.

### CODE REVIEW

**Comment by spirosoik** [comment]
:+1:

**Comment by android10** [comment]
Your approach is valid, I have no doubts. However I will not merge this pull request. Sorry, but what you can do is to fork the repo and create a tag with your approach.
 
In my opinion, an app should not have only one activity, imagine an app with 50 screens (50 fragments managed by only one activity will imply a lot of code to manipulate fragments flows and stacks. It adds way more complexity if you support tablets by the way).

I would definitely use an activity per feature, which will take care of the fragments involved within that feature. Thus, you can also make proper use of dagger by unloading elements not needed within the mentioned feature when the activity die.

**Comment by spirosoik** [comment]
@android10 I think that the title of the pull request is invalid. I suppose that PR of @wkarl is more related with a previous Issue https://github.com/android10/Android-CleanArchitecture/issues/32 . 

I think that is related more with the situation of a dynamic params in a use case. @wkarl implemented a ```Fragment``` Context in order to be able (I suppose) to pass parameters dynamically. 

eg. If I have a login form how I will pass dynamic params in ```UseCase``` when ```UserModule``` is injected with a constructor into the Activity context? 

But I suppose that this will be fixed with plus injection of Dagger instead of creating a Fragment Context. Correct me if I am wrong @wkarl and @android10

**Comment by wkarl** [comment]
@spirosoik This pull request wasn't aimed at #32, I just found it cleaner to have a single Activity.

IMO a Fragment can be used just like an Activity, it has its own lifecycle and is self contained.
My understanding was that the navigator class should take care of the Fragment flow, removing the need to do it all in the Activity.
It has also been a pain to share media with my last multi Activity app and deep linking was more complicated.

@android10 Those are just my thoughts on the topic, I suppose both approaches have their use cases.

**Comment by spirosoik** [comment]
@wkarl :+1: 

@wkarl  for sure @android10 is right that you can't have a single activity with many fragments. The right thing is to plan how deep you want to got and how many activities (with fragments) you want to have. I absolutely agree with @android10 that per feature must be a separate activity. We follow the same approach here.

**Comment by wkarl** [comment]
@spirosoik I think it is simply a question of philosophy. I personally don't want two separate stacks for activities and fragments. 
By the way the reason I came up with this is that Jake Wharton has advocated a single activity approach and doesn't event use fragments (Views with Flow + Mortar). 

It boils down to personal preference which is totally okay for me. Just my two cents :)

**Comment by spirosoik** [comment]
@wkarl Yes I've written this post by Jake Wharton, but this is a general problem with Fragments that's why Jake uses Flow + Mortar.

**Comment by android10** [comment]
I guess this is a matter of taste. I completely agree that both approaches are valid :+1:

**Comment by caseykulm** [comment]
@wkarl @spirosoik btw I don't believe Jake uses Mortar or Flow https://twitter.com/jakewharton/status/442568257141100544

**Comment by wkarl** [comment]
@caseykulm Huh, that's interesting. He clearly stated that he doesn't like to use fragments so I figured he'd use Flow for the view stack: https://twitter.com/jakewharton/status/471703632899887104

**Comment by spirosoik** [comment]
@wkarl Mortar+Flow are a little bit complicated that's why I suppose but I believe that Google maybe will resolve the problems with fragments. MVP is a good solution to face them.

**Comment by cesards** [comment]
> By the way the reason I came up with this is that Jake Wharton has advocated a single activity approach and doesn't event use fragments (Views with Flow + Mortar).
@wkarl That shouldn't ever be a reason to use an architecture. You should analyze if it's convenient to your app (needs). I agree with @android10. I shouldn't ever use an architecture with a single activity because managing navigation in that specific situation can become a pain in the ass...

**Comment by wkarl** [comment]
> That shouldn't ever be a reason to use an architecture. You should analyze if it's convenient to your app (needs).
@cesards Look, I didn't just blindly use this architecture. I have used both approaches and evaluated the pros and cons. There is no silver bullet but for me the single activity approach worked better.

**Comment by cesards** [comment]
:+1: Oki!

**Pull request closed without merging**
