### PR TITLE
Remove android-apt plugin

### PR DESCRIPTION
**Pull request by mapyo**
Thank you this repository!

android-apt is now available in the Android plugin.
ref. https://bitbucket.org/hvisser/android-apt/wiki/Migration

### CODE REVIEW

**Comment by IonutNegru87** [comment]
I confirm that using 'annotationProcessor' is working as expected.

**Comment by mapyo** [comment]
@android10 
Is it possible to see this pr?

**Comment by android10** [comment]
@mapyo I will try to review it this week.

**Comment by mapyo** [comment]
@android10 ping 🙏

**Pull request closed without merging**
