### PR TITLE
Update Gradle plugin to 1.2.3

### PR DESCRIPTION
**Pull request by amouly**
The previous plugin is not working on Android Studio 1.2.

Error details: "Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to..."

### CODE REVIEW

**Comment by android10** [comment]
@amouly Thanks man but I finally did it myself because there is no 1.2.3 version yet! I really appreciate the PR and I also have to check not to break anything when bumping gradle and build tools versions. Since I'm using robolectric, that test module becomes very fragile.

**Comment by amouly** [comment]
@android10 weird, i'm using that version of the plugin from AS 1.2 update. Anyway, maybe we can create an issue? Just for having the record about that.

**Comment by amouly** [comment]
@android10 I just see you updated to 1.2.2. It's ok, I just fixed from the Studio Linter. Anyway thanks for this projects.

**Comment by android10** [comment]
@amouly you are welcome! Feedback is always very important and even more when they want to collaborate :). Cheers!

**Pull request closed without merging**
