### PR TITLE
Integration with retrofit in data network client

### PR DESCRIPTION
**Pull request by andreaguitto**
- optimized data network layer classes
- integrated retrofit in network layer

### CODE REVIEW

**Comment by spirosoik** [comment]
@andreaguitto it's OK but as @android10 mentioned multiple times, wants to keep this repository simple for learning purposes. In your project you can use Retrofit, I did the same also.

**Comment by andreaguitto** [comment]
hi @spirosoik , i appreciate your interest in my work. I think that retrofit is the best way to understand the network layer. Who uses this architecture (with dagger and other rxjava) must have a pretty good knowledge of android and java development. I don't think that the remove of 2 classes and the add of a simple dependency which uses a simple interface with just 2 easy annotations could complicate this architecture. Instead I think that it helps developers in the discovery, use and integration of a well-structured library i their apps. I manage a group of developers, some of them are juniors but they really appreciate simplicity of retrofit. Definitiely I think that retrofit helps the simplicity of architecture because it removes the attention to "Net" classes and focus developer to other packages and layers. The same is for cache classes in wich i working to embed Reservoir.

**Comment by android10** [comment]
@andreaguitto at Soundcloud we are not using Retrofit and I don't see it mandatory for any architecture.

**Comment by andreaguitto** [comment]
@android10 ok, i agree with you it's not a mandatory but we are talking about learning curve of this architecture. Retrofit it's compatible with skills needed for this architecture and and is documented too. Anyway it's yours choice, i hope to be helpful next time. Thank for your answers

**Comment by android10** [comment]
@andreaguitto I really appreciate your effort! The purpose of this is not to learn a library. Api calls are encapsulated in a class already, and as I said, it is an implementation detail, so when it comes to readability you do not need to go into details. 

In the case of RxJava, which is a library, is totally different, since it changes the paradigm and the way of thinking regarding your solution. Dagger is another library, however, nowadays I could not live without any dependency injector.

**Comment by spirosoik** [comment]
@android10 Interesting that in SoundCloud you are not using Retrofit. But because I am curious what are you using?

@andreaguitto the main concept here is to understand the concepts of Clean Architecture combined with Rx, not the HTTP implementation as @android10 mentioned. By the way I don't agree that Retrofit is simpler to understand than the classic HTTP implementation.

**Comment by android10** [comment]
@spirosoik we just use a wrapper around OkHttp, so we have more control over our api calls. Retrofit does too much for my taste.

**Comment by spirosoik** [comment]
@android10 I suppose you mean all this magic via ProxyPattern it's too much.

**Comment by android10** [comment]
@spirosoik :+1:

**Comment by andreaguitto** [comment]
> In the case of RxJava, which is a library, is totally different, since it changes the paradigm and the way of thinking regarding your solution. Dagger is another library, however, nowadays I could not live without any dependency injector.

Totally agreed :heart: 
I just tried to reduce classes in net package using a library which reduces all to a single interface but i understand what you said so this is a closed pull request for me, let's work to other things :headphones:

**Comment by Fshamri** [comment]
i believe Retrofit becomes as important part of any android projects nowadays, therefore it is worth to be included here

**Comment by android10** [comment]
@Fshamri again, this discussion about an implementation detail does not make any sense. Is up to the developer to use any library and Retrofit has nothing to do with the concept of Clean Architecture.

**Comment by android10** [comment]
@andreaguitto Thanks so much for understanding buddy. I really like people like you collaborating.
And from this kind of discussions, we all learn, which is the reason why we are here :).

**Comment by spirosoik** [comment]
@android10 Totally agreed. Let's go for :beers: guys

**Comment by android10** [comment]
Yeah! For the win! :+1: :smile:

**Comment by spirosoik** [comment]
@android10 As you said, I am trying to learn new things by everyone and to help to this great effort. You inspired us with this repository and the whole philosophy of clean architecture. So I want to thank you for this dude.

**Comment by Fshamri** [comment]
@android10 I really appreciate your efforts to spread knowledge

**Comment by android10** [comment]
I'm closing this one guys.

**Pull request closed without merging**
