### PR TITLE
Merging with master

### PR DESCRIPTION
**Pull request by AshwinNBhanushali**

### CODE REVIEW

**Comment by android10** [comment]
@AshwinNBhanushali I cannot approve the pull request cause I'm gonna change the presentation layer for learning purpose and I'm not interested in MVVM yet.

**Review by fn850085 — COMMENTED** [review]
Go

**Comment by fn850085** [comment]
Community

**Comment by fn850085** [comment]
Leave community

**Comment by fn850085** [comment]
Leave a community

**Comment by fn850085** [comment]
200

**Comment by fn850085** [comment]
https://github.com/android10/Android-CleanArchitecture/pull/6

**Comment by fn850085** [comment]
Leave a community

**Review by fn850085 — COMMENTED** [review]
Leave a community

**Comment by fn850085** [comment]
Leave a community

**Pull request closed without merging**
