### PR TITLE
Remove static and final modifiers on RestApi interface

### PR DESCRIPTION
**Pull request by lalongooo**

### CODE REVIEW

**Comment by spirosoik** [comment]
:+1:

**Comment by android10** [comment]
:+1: Thanks!

**Comment by alexandru-calinoiu** [comment]
Why?

**Comment by spirosoik** [comment]
@alexandru-calinoiu first of all modified are redundant in an interface.Every field declaration in the body of an interface is implicitly public, static, and final. It is permitted to redundantly specify any or all of these modifiers for such fields.

Also it's generally a bad practice to define a Constant variable in an Interface. The problem is that the constants are part of the public "interface" of the implementing class. This means that the implementing class is publishing all of these values to external classes even when they are only required internally.

**Comment by alexandru-calinoiu** [comment]
@spirosoik thanks you.

**Comment by spirosoik** [comment]
@alexandru-calinoiu welcome :+1:

**Pull request merged**
